/* Basic guards for the crops JSON data layer: schema sanity, per-crop anchors
 * in the generated page, source-registry integrity, and a drift check between
 * data/crops.json and database/crops.html. */
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");

const root = path.resolve(__dirname, "..");
const data = JSON.parse(fs.readFileSync(path.join(root, "data", "crops.json"), "utf8"));
const html = fs.readFileSync(path.join(root, "database", "crops.html"), "utf8");

const LEVELS = new Set(data.meta.evidenceLevels);
const VALIDITY = new Set(data.meta.validityValues);
const SOURCE_KINDS = new Set(["official-news", "steam-thread", "local-video", "wiki", "local-archive", "community-scan", "store-page"]);
const SOURCE_IDS = new Set(Object.keys(data.sources));
assert.ok(LEVELS.size === 5 && VALIDITY.size === 4, "meta must enumerate evidence levels and validity values");

for (const [id, src] of Object.entries(data.sources)) {
  assert.ok(SOURCE_KINDS.has(src.kind), `source ${id}: bad kind ${src.kind}`);
  assert.ok(src.title && src.date, `source ${id}: title and date are required`);
  assert.ok("url" in src && "build" in src, `source ${id}: url (may be null) and build fields are required`);
}

function checkFact(fact, where) {
  assert.ok(LEVELS.has(fact.evidenceLevel), `${where}: bad evidenceLevel ${fact.evidenceLevel}`);
  assert.ok(VALIDITY.has(fact.validity), `${where}: bad validity ${fact.validity}`);
  assert.ok("build" in fact, `${where}: build field required (may be null)`);
  assert.ok(fact.text, `${where}: fact needs text`);
  assert.ok(Array.isArray(fact.sourceIds) && fact.sourceIds.length > 0, `${where}: fact needs sourceIds`);
  for (const id of fact.sourceIds) assert.ok(SOURCE_IDS.has(id), `${where}: unknown source id ${id}`);
}

const entries = data.crops.concat(data.inputs);
for (const entry of entries) {
  assert.ok(entry.id && entry.name && entry.lastUpdated, `entry missing id/name/lastUpdated: ${entry.id}`);
  assert.match(html, new RegExp(`id="${entry.id}" data-search-entry`), `generated page must expose #${entry.id} anchor`);
  for (const field of entry.fields) {
    for (const fact of field.facts) checkFact(fact, `${entry.id}/${field.key}`);
  }
}
for (const fact of data.cashin) checkFact(fact, "cashin");

/* Fact-count sanity with tolerance — do not hardcode an exact number. */
const factCount = entries.reduce((n, e) => n + e.fields.reduce((m, f) => m + f.facts.length, 0), 0) + data.cashin.length;
assert.ok(factCount >= 20, `expected at least 20 facts, got ${factCount}`);

/* Sell-price discipline: no per-crop player sell price may be asserted while the settlement screen stays aggregated. */
const sellFacts = data.crops.flatMap((c) => c.fields.filter((f) => f.key === "sell").flatMap((f) => f.facts));
for (const fact of sellFacts) {
  assert.ok(!/sell price[^.]*\bis\s+\d/i.test(fact.text), `per-crop sell price asserted without evidence: ${fact.text.slice(0, 60)}`);
}

/* Garlic's 31C must stay labeled as retail, never as a seed or sell price. */
const garlic = data.crops.find((c) => c.id === "garlic");
assert.ok(garlic.fields.every((f) => f.key !== "seed" || !/31C/.test(f.facts.map((x) => x.text).join(" "))), "31C must not appear as garlic seed price");

/* The generated file must be byte-identical to a fresh render. */
assert.match(html, /GENERATED by scripts\/build-crops\.cjs/);
const drift = spawnSync(process.execPath, [path.join(root, "scripts", "build-crops.cjs"), "--check"], { cwd: root, encoding: "utf8" });
assert.equal(drift.status, 0, `database/crops.html drift detected — re-run node scripts/build-crops.cjs\n${drift.stdout}${drift.stderr}`);

console.log(`PASS: crops data layer — ${data.crops.length} crops, ${data.inputs.length} inputs, ${factCount} facts, generated page in sync.`);
