/* Basic guards for the animals JSON data layer: schema sanity, per-animal
 * anchors in the generated page, and a drift check between data/animals.json
 * and database/animals.html. */
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");

const root = path.resolve(__dirname, "..");
const data = JSON.parse(fs.readFileSync(path.join(root, "data", "animals.json"), "utf8"));
const html = fs.readFileSync(path.join(root, "database", "animals.html"), "utf8");

const LEVELS = new Set(data.meta.evidenceLevels);
assert.ok(LEVELS.size >= 7, "meta.evidenceLevels must enumerate all evidence levels");
assert.ok(Array.isArray(data.species) && data.species.length >= 4, "expected at least 4 species");

for (const animal of data.species) {
  assert.ok(animal.id && animal.name && animal.lastUpdated, `species missing id/name/lastUpdated: ${animal.id}`);
  assert.match(html, new RegExp(`id="${animal.id}" data-search-entry`), `generated page must expose #${animal.id} anchor`);
  for (const field of animal.fields) {
    for (const fact of field.facts) {
      assert.ok(LEVELS.has(fact.evidence), `${animal.id}/${field.key}: bad evidence level ${fact.evidence}`);
      assert.ok(fact.text && fact.source, `${animal.id}/${field.key}: fact needs text and source`);
    }
  }
}

/* Chicken is the reference species: every core field must be populated. */
const chicken = data.species.find((a) => a.id === "chicken");
const chickenFields = new Set(chicken.fields.map((f) => f.key));
for (const key of ["acquisition", "housing", "feed", "water", "products", "breeding", "sickness", "automation", "quests", "bugs", "selling"]) {
  assert.ok(chickenFields.has(key), `chicken profile must cover ${key}`);
}

/* Non-chicken species must mark unverified fields with labeled facts, not invented values. */
for (const animal of data.species.filter((a) => a.id !== "chicken")) {
  const levels = new Set(animal.fields.flatMap((f) => f.facts.map((fact) => fact.evidence)));
  assert.ok(levels.has("unknown") || levels.has("official-pre-ea") || levels.has("reported-single-source"), `${animal.id} must label unverified data`);
}

/* The generated file must be byte-identical to a fresh render. */
assert.match(html, /GENERATED by scripts\/build-animals\.cjs/);
const drift = spawnSync(process.execPath, [path.join(root, "scripts", "build-animals.cjs"), "--check"], { cwd: root, encoding: "utf8" });
assert.equal(drift.status, 0, `database/animals.html drift detected — re-run node scripts/build-animals.cjs\n${drift.stdout}${drift.stderr}`);

console.log(`PASS: animals data layer — ${data.species.length} species, ${data.species.reduce((n, a) => n + a.fields.length, 0)} field groups, generated page in sync.`);
